export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const FETCH_USERINFO = 'FETCH_USERINFO';
export const FETCH_USERINFO_FULFILLED = 'FETCH_USERINFO_FULFILLED';
export const FETCH_USERINFO_REJECTED = 'FETCH_USERINFO_REJECTED';
