export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const FETCH_MYINFO_REQUEST = 'FETCH_MYINFO_REQUEST';
export const FETCH_MYINFO_SUCCESS = 'FETCH_MYINFO_SUCCESS';
export const FETCH_MYINFO_FAILURE = 'FETCH_MYINFO_FAILURE';

export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';

export const FETCH_NEW_NOTIFICATIONS_REQUEST = 'FETCH_NEW_NOTIFICATIONS_REQUEST';
export const FETCH_NEW_NOTIFICATIONS_SUCCESS = 'FETCH_NEW_NOTIFICATIONS_SUCCESS';
export const FETCH_NEW_NOTIFICATIONS_FAILURE = 'FETCH_NEW_NOTIFICATIONS_FAILURE';

export const FETCH_OLD_NOTIFICATIONS_REQUEST = 'FETCH_OLD_NOTIFICATIONS_REQUEST';
export const FETCH_OLD_NOTIFICATIONS_SUCCESS = 'FETCH_OLD_NOTIFICATIONS_SUCCESS';
export const FETCH_OLD_NOTIFICATIONS_FAILURE = 'FETCH_OLD_NOTIFICATIONS_FAILURE';

export const FETCH_NOTIFICATION_CHECK_TIME_REQUEST = 'FETCH_NOTIFICATION_CHECK_TIME_REQUEST';
export const FETCH_NOTIFICATION_CHECK_TIME_SUCCESS = 'FETCH_NOTIFICATION_CHECK_TIME_SUCCESS';
export const FETCH_NOTIFICATION_CHECK_TIME_FAILURE = 'FETCH_NOTIFICATION_CHECK_TIME_FAILURE';
