export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const FETCH_MYINFO_REQUEST = 'FETCH_MYINFO_REQUEST';
export const FETCH_MYINFO_SUCCESS = 'FETCH_MYINFO_SUCCESS';
export const FETCH_MYINFO_FAILURE = 'FETCH_MYINFO_FAILURE';

export const FETCH_MY_NOTIFICATIONS_REQUEST = 'FETCH_MY_NOTIFICATIONS_REQUEST';
export const FETCH_MY_NOTIFICATIONS_SUCCESS = 'FETCH_MY_NOTIFICATIONS_SUCCESS';
export const FETCH_MY_NOTIFICATIONS_FAILURE = 'FETCH_MY_NOTIFICATIONS_FAILURE';
