export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export const FETCH_NEW_PARENT_COMMENT_REQUEST = 'FETCH_NEW_PARENT_COMMENT_REQUEST';
export const FETCH_NEW_PARENT_COMMENT_SUCCESS = 'FETCH_NEW_PARENT_COMMENT_SUCCESS';
export const FETCH_NEW_PARENT_COMMENT_FAILURE = 'FETCH_NEW_PARENT_COMMENT_FAILURE';

export const FETCH_NEW_CHILD_COMMENT_REQUEST = 'FETCH_NEW_CHILD_COMMENT_REQUEST';
export const FETCH_NEW_CHILD_COMMENT_SUCCESS = 'FETCH_NEW_CHILD_COMMENT_SUCCESS';
export const FETCH_NEW_CHILD_COMMENT_FAILURE = 'FETCH_NEW_CHILD_COMMENT_FAILURE';

export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';

export const REMOVE_COMMENT = 'REMOVE_COMMENT';

export const CHECK_CACHE_AND_UPDATE_COMMENT = 'CHECK_CACHE_AND_UPDATE_COMMENT';

export const FETCH_UPDATED_COMMENT_REQUEST = 'FETCH_UPDATED_COMMENT_REQUEST';
export const FETCH_UPDATED_COMMENT_SUCCESS = 'FETCH_UPDATED_COMMENT_SUCCESS';
export const FETCH_UPDATED_COMMENT_FAILURE = 'FETCH_UPDATED_COMMENT_FAILURE';

export const START_EDITING_COMENT = 'START_EDITING_COMENT';
export const SAVE_EDITING_COMENT = 'SAVE_EDITING_COMENT';
export const EDITING_COMMENT_DONE = 'EDITING_COMMENT_DONE';

export const LOAD_EDITING_COMMENT = 'LOAD_EDITING_COMMENT';
