export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';

export const GET_COMMENT_REQUEST = 'GET_COMMENT_REQUEST';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAILURE = 'GET_COMMENT_FAILURE';

export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';

export const REMOVE_COMMENT = 'REMOVE_COMMENT';

export const CHECK_CACHE_AND_UPDATE_COMMENT = 'CHECK_CACHE_AND_UPDATE_COMMENT';

export const FETCH_UPDATED_COMMENT_REQUEST = 'FETCH_UPDATED_COMMENT_REQUEST';
export const FETCH_UPDATED_COMMENT_SUCCESS = 'FETCH_UPDATED_COMMENT_SUCCESS';
export const FETCH_UPDATED_COMMENT_FAILURE = 'FETCH_UPDATED_COMMENT_FAILURE';
