export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

export const LOAD_POSTS = 'LOAD_POSTS';
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';

export const FETCH_NEW_POST_REQUEST = 'GET_POST_REQUEST';
export const FETCH_NEW_POST_SUCCESS = 'GET_POST_SUCCESS';
export const FETCH_NEW_POST_FAILURE = 'GET_POST_FAILURE';

export const FETCH_POST_CONTENTS_REQUEST = 'FETCH_POST_CONTENTS_REQUEST';
export const FETCH_POST_CONTENTS_SUCCESS = 'FETCH_POST_CONTENTS_SUCCESS';
export const FETCH_POST_CONTENTS_FAILURE = 'FETCH_POST_CONTENTS_FAILURE';

export const LOAD_POST = 'LOAD_POST';
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS';
