export const SSR_POST_LIST_PAGE = 'SSR_POST_LIST_PAGE';
export const SSR_POST_PAGE = 'SSR_POST_PAGE';
export const SSR_EDIT_POST_PAGE = 'SSR_EDIT_POST_PAGE';
export const SSR_WRITE_POST_PAGE = 'SSR_WRITE_POST_PAGE';
export const SSR_COMMON_PAGE = 'SSR_COMMON_PAGE';
