export const ADD_TOAST_NOTIFICATION = 'ADD_TOAST_NOTIFICATION';
export const REMOVE_TOAST_NOTIFICATION = 'REMOVE_TOAST_NOTIFICATION';
export const CLEAR_TOAST_NOTIFICATIONS = 'CLEAR_TOAST_NOTIFICATIONS';
